import {
  LayoutDashboard,
  Store,
  GitBranch,
  Package,
  ShoppingBag,
  Truck,
  ClipboardList,
  MonitorSmartphone,
  Users,
  UserCog,
  BarChart3,
  Brain,
  Bell,
  Settings,
  LifeBuoy,
  LogOut,
  TrendingUp,
  History,
  MessageSquare,
  Boxes,
  LayoutGrid,
  Armchair,
  Building2,
  FileText,
  SlidersHorizontal,
  Activity,
  ChefHat,
  UtensilsCrossed,
  AlertTriangle,
  ArrowLeftRight,
  ShoppingCart,
  Heart,
  Gift,
  CalendarDays,
  Clock,
  UserCheck,
  Wallet,
  Gauge,
  LineChart,
  Lightbulb,
  FileSpreadsheet,
  Sparkles,
  Workflow,
  CalendarClock,
  ShieldCheck,
  KeyRound,
  Link2,
  ServerCog,
  FolderKanban,
} from 'lucide-react'

/**
 * Enterprise navigation — operations MDM + catalog/procurement + ML modules.
 */
export const NAV_SECTIONS = [
  {
    id: 'overview',
    label: 'Overview',
    items: [
      { to: '/', label: 'Dashboard', icon: LayoutDashboard, end: true },
      { to: '/ops', label: 'Operations', icon: Activity },
      { to: '/catalog', label: 'Catalog hub', icon: ShoppingCart },
    ],
  },
  {
    id: 'operations',
    label: 'Master data',
    items: [
      { to: '/restaurants', label: 'Restaurants', icon: Store },
      { to: '/restaurant-profile', label: 'Restaurant profile', icon: Building2 },
      { to: '/branches', label: 'Branches', icon: GitBranch },
      { to: '/dining-areas', label: 'Dining areas', icon: LayoutGrid },
      { to: '/tables', label: 'Tables', icon: Armchair },
      { to: '/departments', label: 'Departments', icon: Boxes },
      { to: '/business-settings', label: 'Business settings', icon: SlidersHorizontal },
      { to: '/documents', label: 'Documents', icon: FileText },
      { to: '/orders', label: 'Orders', icon: ClipboardList },
      { to: '/pos', label: 'POS', icon: MonitorSmartphone },
      { to: '/kitchen', label: 'Kitchen (KDS)', icon: ChefHat },
      { to: '/floor', label: 'Floor plan', icon: LayoutGrid },
      { to: '/payments', label: 'Payments', icon: ShoppingCart },
      { to: '/customers', label: 'Customers', icon: Users },
    ],
  },
  {
    id: 'catalog',
    label: 'Catalog & Supply',
    items: [
      { to: '/products', label: 'Products', icon: ShoppingBag },
      { to: '/categories', label: 'Categories', icon: Boxes },
      { to: '/units', label: 'Units', icon: Package },
      { to: '/suppliers', label: 'Suppliers', icon: Truck },
      { to: '/warehouses', label: 'Warehouses', icon: Building2 },
      { to: '/stock', label: 'Stock', icon: Package },
      { to: '/purchase-orders', label: 'Purchase orders', icon: ClipboardList },
      { to: '/goods-receipts', label: 'Goods receipts', icon: Package },
      { to: '/recipes', label: 'Recipes', icon: ChefHat },
      { to: '/menu', label: 'Menu', icon: UtensilsCrossed },
      { to: '/stock-alerts', label: 'Stock alerts', icon: AlertTriangle },
      { to: '/stock-transfers', label: 'Transfers', icon: ArrowLeftRight },
      { to: '/inventory-transactions', label: 'Stock ledger', icon: History },
      { to: '/inventory', label: 'Inventory AI', icon: Package },
    ],
  },
  {
    id: 'crm-hrms',
    label: 'CRM & HR',
    items: [
      { to: '/crm', label: 'Customer CRM', icon: Heart },
      { to: '/loyalty', label: 'Loyalty', icon: Gift },
      { to: '/reservations', label: 'Reservations', icon: CalendarDays },
      { to: '/hrms', label: 'HR Dashboard', icon: LayoutDashboard },
      { to: '/shifts', label: 'Shifts', icon: Clock },
      { to: '/attendance', label: 'Attendance', icon: UserCheck },
      { to: '/leaves', label: 'Leaves', icon: CalendarDays },
      { to: '/payroll', label: 'Payroll', icon: Wallet },
    ],
  },
  {
    id: 'people',
    label: 'People',
    items: [
      { to: '/employees', label: 'Employees', icon: UserCog },
      { to: '/staff', label: 'Staff Planner', icon: Boxes },
    ],
  },
  {
    id: 'intelligence',
    label: 'Intelligence & BI',
    items: [
      { to: '/executive', label: 'Executive BI', icon: Gauge },
      { to: '/analytics-center', label: 'Analytics Center', icon: BarChart3 },
      { to: '/forecast-bi', label: 'Forecasts', icon: LineChart },
      { to: '/insights', label: 'Insights & Alerts', icon: Lightbulb },
      { to: '/reports-center', label: 'Reports Center', icon: FileSpreadsheet },
      { to: '/ai-assistant', label: 'AI Assistant', icon: Sparkles },
      { to: '/forecast', label: 'Forecast AI', icon: Brain },
      { to: '/analytics', label: 'Model Reports', icon: TrendingUp },
      { to: '/history', label: 'History', icon: History },
      { to: '/feedback', label: 'Feedback', icon: MessageSquare },
    ],
  },
  {
    id: 'automation-admin',
    label: 'Automation Admin',
    items: [
      { to: '/admin-console', label: 'Admin Console', icon: ServerCog },
      { to: '/workflow-builder', label: 'Workflow Builder', icon: Workflow },
      { to: '/notification-center', label: 'Notification Center', icon: Bell },
      { to: '/job-scheduler', label: 'Job Scheduler', icon: CalendarClock },
      { to: '/report-scheduler', label: 'Report Scheduler', icon: FileSpreadsheet },
      { to: '/audit-center', label: 'Audit Center', icon: History },
      { to: '/system-settings', label: 'System Settings', icon: Settings },
      { to: '/file-management', label: 'File Management', icon: FolderKanban },
      { to: '/api-management', label: 'API Management', icon: KeyRound },
      { to: '/integrations', label: 'Integrations', icon: Link2 },
      { to: '/health-dashboard', label: 'Health Dashboard', icon: Activity },
      { to: '/security-center', label: 'Security Center', icon: ShieldCheck },
    ],
  },
  {
    id: 'system',
    label: 'System',
    items: [
      { to: '/notifications', label: 'Notifications', icon: Bell },
      { to: '/settings', label: 'Settings', icon: Settings },
      { to: '/support', label: 'Support', icon: LifeBuoy },
      { to: '/profile', label: 'Profile', icon: TrendingUp, hiddenInSidebar: true },
      { to: '/sessions', label: 'Sessions', icon: MonitorSmartphone, hiddenInSidebar: true },
    ],
  },
]

export const SIDEBAR_LOGOUT = { id: 'logout', label: 'Logout', icon: LogOut }

export const BREADCRUMB_LABELS = {
  '': 'Dashboard',
  ops: 'Operations',
  catalog: 'Catalog hub',
  restaurants: 'Restaurants',
  'restaurant-profile': 'Restaurant profile',
  branches: 'Branches',
  'dining-areas': 'Dining areas',
  tables: 'Tables',
  departments: 'Departments',
  'business-settings': 'Business settings',
  documents: 'Documents',
  inventory: 'Inventory AI',
  stock: 'Stock',
  products: 'Products',
  categories: 'Categories',
  units: 'Units',
  suppliers: 'Suppliers',
  warehouses: 'Warehouses',
  'purchase-orders': 'Purchase orders',
  'goods-receipts': 'Goods receipts',
  recipes: 'Recipes',
  menu: 'Menu',
  'stock-alerts': 'Stock alerts',
  'stock-transfers': 'Transfers',
  'inventory-transactions': 'Stock ledger',
  orders: 'Orders',
  pos: 'POS',
  kitchen: 'Kitchen display',
  floor: 'Floor plan',
  payments: 'Payments',
  customers: 'Customers',
  crm: 'Customer CRM',
  loyalty: 'Loyalty',
  reservations: 'Reservations',
  hrms: 'HR Dashboard',
  shifts: 'Shifts',
  attendance: 'Attendance',
  leaves: 'Leaves',
  payroll: 'Payroll',
  employees: 'Employees',
  staff: 'Staff Planner',
  reports: 'Reports',
  analytics: 'Model Reports',
  executive: 'Executive BI',
  'analytics-center': 'Analytics Center',
  'forecast-bi': 'Forecasts',
  insights: 'Insights & Alerts',
  'reports-center': 'Reports Center',
  'ai-assistant': 'AI Assistant',
  'admin-console': 'Admin Console',
  'workflow-builder': 'Workflow Builder',
  'notification-center': 'Notification Center',
  'job-scheduler': 'Job Scheduler',
  'report-scheduler': 'Report Scheduler',
  'system-settings': 'System Settings',
  'audit-center': 'Audit Center',
  'file-management': 'File Management',
  'api-management': 'API Management',
  integrations: 'Integrations',
  'health-dashboard': 'Health Dashboard',
  'security-center': 'Security Center',
  forecast: 'Forecast AI',
  notifications: 'Notifications',
  settings: 'Settings',
  support: 'Support',
  profile: 'Profile',
  sessions: 'Sessions',
  history: 'History',
  feedback: 'Feedback',
  unauthorized: 'Unauthorized',
}

/** Paths allowed per role (wildcard-friendly). */
export const ROLE_PATHS = {
  SUPER_ADMIN: ['*'],
  ADMIN: ['*'],
  MANAGER: ['*'],
  EMPLOYEE: [
    '/',
    '/forecast',
    '/staff',
    '/inventory',
    '/products',
    '/orders',
    '/pos',
    '/kitchen',
    '/floor',
    '/payments',
    '/menu',
    '/catalog',
    '/hrms',
    '/attendance',
    '/leaves',
    '/profile',
    '/sessions',
    '/notifications',
    '/support',
  ],
}
